backend:
  name: github
  repo: kerr325/netlify-cms-playground-spike

media_folder: media

collections:
  - name: page
    label: Page
    folder: pages
    create: true
    fields:
      - {name: title, label: Title}
      - {name: body, label: Body, widget: markdown}